// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTPX3KX8Heq774w30nTl3YKhmd4v3OUQ',
    appId: '1:47114816492:web:b5e043db762d5ecf4c8ec9',
    messagingSenderId: '47114816492',
    projectId: 'email-abc05',
    authDomain: 'email-abc05.firebaseapp.com',
    storageBucket: 'email-abc05.appspot.com',
    measurementId: 'G-5MNQCVZ5G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADfabc4uGKQiRAMoQX0IMMKWP5RnaHwEU',
    appId: '1:47114816492:android:93b1d1f5ff7003d04c8ec9',
    messagingSenderId: '47114816492',
    projectId: 'email-abc05',
    storageBucket: 'email-abc05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl0waJ-JpBaGASKYifgVwtizN7KnY8PHg',
    appId: '1:47114816492:ios:cca1fa61153b10914c8ec9',
    messagingSenderId: '47114816492',
    projectId: 'email-abc05',
    storageBucket: 'email-abc05.appspot.com',
    iosClientId: '47114816492-93rcfhrjnd4hudj5c7af947plbt4js6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.allTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl0waJ-JpBaGASKYifgVwtizN7KnY8PHg',
    appId: '1:47114816492:ios:cca1fa61153b10914c8ec9',
    messagingSenderId: '47114816492',
    projectId: 'email-abc05',
    storageBucket: 'email-abc05.appspot.com',
    iosClientId: '47114816492-93rcfhrjnd4hudj5c7af947plbt4js6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.allTogether',
  );
}
